- hosts: localhost
  tasks:
    - name: Get some facts from Insights
      insights: 
        plugins:
          "demo.rules.fobmaster.report":
             foo: 4

    - debug: var=insights.fobmaster_report.foo

    - name: Get some more facts from Insights
      insights: 
        plugins:
          "insights.parsers.hostname.Hostname":
          "demo.rules.fobmaster.report":
          "demo.rules.sample_script.report":
          "demo.rules.stand_alone.report":

    - debug: var=insights
